port: 7880
rtc:
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
  tcp_port: 7881
  udp_port: 7882

redis:
  address: redis:6379

keys:
  RYKAXVztBmSn8qjusGLI6WT9gr2fc30v: hofkLYXCzx24DdO1n6FZbJeAB5NTWuc9

room:
  auto_create: true
  empty_timeout: 300
  max_participants: 50

turn:
  enabled: false

logging:
  level: info
  json: false
