port: 7880
rtc:
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
  tcp_port: 7881
  udp_port: 7882

redis:
  address: redis:6379

keys:
  devkey: secret

room:
  auto_create: true
  empty_timeout: 300
  max_participants: 50

turn:
  enabled: true
  domain: localhost
  tls_port: 5349
  udp_port: 3478
  external_tls: false

logging:
  level: info
  json: false
