port: 7880

rtc:
  port_range_start: 50000
  port_range_end: 50100
  tcp_port: 7881
  use_external_ip: false

redis:
  address: localhost:6379

keys:
  devkey: secret

room:
  auto_create: true
  empty_timeout: 300
  max_participants: 20

logging:
  level: info